### ISSUE TITLE
Error: partial write: field type conflict: input field \"ups.load\" 

### ISSUE THREAD

**Issue by grigsby** [mihai-cindea/nut-influxdb-exporter#11]
I just installed a new APC UPS, and the docker image is now giving an error data type conflict and can't write to Influxdb. See log below.

It was working fine with my old -- ancient -- APC UPS. The new one is an APC BN1500M2.

https://www.apc.com/shop/us/en/products/Back-UPS-PRO-BN-1500VA-10-Outlets-2-USB-Charging-Ports-AVR-LCD-interface/P-BN1500M2

Any ideas?

Thank you!

```
Connecting to InfluxDB host:192.168.1.4, DB:telegraf
Connected successfully to InfluxDB
INFLUXDB_DATABASE: telegraf
INFLUXDB_USER:
INFLUXDB_PORT: 8086
INFLUXDB_HOST: 192.168.1.4
NUT_USER: nutslave
UPS_NAME qnapups
INTERVAL: 21.0
VERBOSE: true
Connecting to NUT host 192.168.1.4:3493
[DEBUG] Class initialization...
[DEBUG] -> Host = 192.168.1.4 (port 3493)
[DEBUG] -> Login = 'nutslave' / 'nutslave'
[DEBUG] Connecting to host
Connected successfully to NUT
[DEBUG] list_vars called...
[{'measurement': 'ups_status', 'fields': {'battery.charge': 99, 'battery.charge.low': 10, 'battery.charge.warning': 50, 'battery.date': '2001/09/25', 'battery.runtime': 2739, 'battery.runtime.low': 120, 'battery.voltage': 27.3, 'battery.voltage.nominal': 24.0, 'driver.parameter.pollfreq': 30, 'driver.parameter.pollinterval': 2, 'driver.parameter.port': 'auto', 'driver.parameter.synchronous': 'no', 'input.sensitivity': 'medium', 'input.transfer.high': 142, 'input.transfer.low': 88, 'input.voltage': 121.0, 'input.voltage.nominal': 120, 'ups.delay.shutdown': 20, 'ups.firmware': '957.e4 .D', 'ups.firmware.aux': 'e4', 'ups.load': 15, 'ups.mfr.date': '2020/08/08', 'ups.realpower.nominal': 900, 'ups.status': 'OL CHRG', 'ups.test.result': 'No test initiated', 'ups.timer.reboot': 0, 'ups.timer.shutdown': -1, 'watts': 135.0}, 'tags': {'host': 'citadel', 'battery.type': 'PbAc', 'device.mfr': 'American Power Conversion', 'device.model': 'Back-UPS NS 1500M2', 'device.serial': '4B2032P27636', 'device.type': 'ups', 'driver.version': '2.7.4.1', 'driver.version.data': 'APC HID 0.96', 'ups.mfr': 'American Power Conversion', 'ups.model': 'Back-UPS NS 1500M2', 'ups.productid': '0002', 'ups.serial': '4B2032P27636', 'ups.vendorid': '051d'}}]
[DEBUG] http://192.168.1.4:8086 "POST /write?db=telegraf HTTP/1.1" 400 151
Traceback (most recent call last):
File "/src/nut-influxdb-exporter.py", line 113, in <module>
print(client.write_points(json_body))
File "/usr/local/lib/python3.8/site-packages/influxdb/client.py", line 594, in write_points
return self._write_points(points=points,
File "/usr/local/lib/python3.8/site-packages/influxdb/client.py", line 672, in _write_points
self.write(
File "/usr/local/lib/python3.8/site-packages/influxdb/client.py", line 404, in write
self.request(
File "/usr/local/lib/python3.8/site-packages/influxdb/client.py", line 369, in request
raise InfluxDBClientError(err_msg, response.status_code)
influxdb.exceptions.InfluxDBClientError: 400: {"error":"partial write: field type conflict: input field \"ups.load\" on measurement \"ups_status\" is type integer, already exists as type float dropped=1"}

Error connecting to InfluxDB.
```

**Comment by mcindea** [comment]
Hmm, after a quick looks it seems that there's a conflict with the already existing data types. Did you forward the new APC to the old DB name? 
Did you try using another db name? It seems the new data has `ups.load` type integer while the old one was float, so I think it's more of a InfluxDB issue.

**Comment by grigsby** [comment]
Yes, you are correct. I was sending the data to the old DB. Sending it to a new DB (with no previously existing data) works. I'm not good enough at DB management or InfluxDB to know if this should be bothersome, but it's working now, so I guess it's all good. Thanks for your help, and for giving us a cool utility!

**Comment by mcindea** [comment]
Awesome, glad it works! :)
