### ISSUE TITLE
NameError: name 'ups_data' is not defined

### ISSUE THREAD

**Issue by agit22** [mihai-cindea/nut-influxdb-exporter#3]
I'm having trouble connecting to NUT on a different machine than my unraid box.
I'm at a bit of a loss on what the issue is.

Here's my config
[https://imgur.com/Ufbklop](https://imgur.com/Ufbklop)
pfsense config
[https://imgur.com/a/u1m9vrY](https://imgur.com/a/u1m9vrY)
And docker log

```
Traceback` (most recent call last):
File "/src/nut-influxdb-exporter.py", line 107, in <module>
json_body = construct_object(ups_data, remove_keys, tag_keys)
NameError: name 'ups_data' is not defined
Connecting to InfluxDB host:10.0.0.44, DB:nut
Connected successfully to InfluxDB
INFLUXDB_DATABASE: nut
INFLUXDB_USER: admin
INFLUXDB_PORT: 8086
INFLUXDB_HOST: 10.0.0.44
NUT_USER: monuser
UPS_ALIAS UPS
INTERVAL: 21.0
VERBOSE: true
Connecting to NUT host 10.0.0.1:3493
[DEBUG] Class initialization...
[DEBUG] -> Host = 10.0.0.1 (port 3493)
[DEBUG] -> Login = 'monuser' / '1234'
[DEBUG] Connecting to host
Connected successfully to NUT
[DEBUG] list_vars called...
Traceback (most recent call last):
File "/src/nut-influxdb-exporter.py", line 100, in <module>
ups_data = ups_client.list_vars(ups_alias)
File "/usr/local/lib/python3.7/site-packages/nut2.py", line 160, in list_vars
raise PyNUTError(result.replace("\n", ""))
nut2.PyNUTError: ERR UNKNOWN-UPS

Error getting data from NUT

Traceback (most recent call last):
File "/src/nut-influxdb-exporter.py", line 107, in <module>
json_body = construct_object(ups_data, remove_keys, tag_keys)
NameError: name 'ups_data' is not defined

```

**Comment by mcindea** [comment]
Hmm, interesting. I didn't know PfSense has a NUT plugin.
It seems more like a problem with NUT or Nut2 Python library, not recognizing the UPS. When querying them, it just returns `ERR UNKNOWN-UPS`.
What kind of UPS Vendor are you using?

**Comment by mcindea** [comment]
I figured it out: The problem is the UPS name, and I don't know if we have a variable yet in Unraid for the name. Did some tests locally, where the name of my `UPS` is really `UPS`:
```
root@Rick:~# nc localhost 3493 -v
Rick [127.0.0.1] 3493 (nut) open
USERNAME <>
OK
PASSWORD <>
OK
LIST VAR UPS
BEGIN LIST VAR UPS
VAR UPS battery.charge "100"
VAR UPS battery.charge.low "10"
VAR UPS battery.charge.warning "20"
VAR UPS battery.mfr.date "CPS"
VAR UPS battery.runtime "2250"
VAR UPS battery.runtime.low "300"
VAR UPS battery.type "PbAcid"
VAR UPS battery.voltage "24.0"
VAR UPS battery.voltage.nominal "24"
VAR UPS device.mfr "CPS"
VAR UPS device.model "CP1500EPFCLCD"
VAR UPS device.serial "CRMJP2000104"
VAR UPS device.type "ups"
VAR UPS driver.name "usbhid-ups"
VAR UPS driver.parameter.pollfreq "30"
VAR UPS driver.parameter.pollinterval "2"
VAR UPS driver.parameter.port "auto"
VAR UPS driver.parameter.synchronous "no"
VAR UPS driver.version "2.7.4.1"
VAR UPS driver.version.data "CyberPower HID 0.5"
VAR UPS driver.version.internal "0.53"
VAR UPS driver.version.usb "libusb-1.0.22 (API: 0x1000106)"
VAR UPS input.transfer.high "260"
VAR UPS input.transfer.low "170"
VAR UPS input.voltage "221.0"
VAR UPS input.voltage.nominal "230"
VAR UPS output.voltage "269.0"
VAR UPS ups.beeper.status "enabled"
VAR UPS ups.delay.shutdown "20"
VAR UPS ups.delay.start "30"
VAR UPS ups.load "22"
VAR UPS ups.mfr "CPS"
VAR UPS ups.model "CP1500EPFCLCD"
VAR UPS ups.productid "0501"
VAR UPS ups.realpower.nominal "900"
VAR UPS ups.serial "CRMJP2000104"
VAR UPS ups.status "OL"
VAR UPS ups.test.result "No test initiated"
VAR UPS ups.timer.shutdown "-60"
VAR UPS ups.timer.start "-60"
VAR UPS ups.vendorid "0764"
END LIST VAR UPS
```

and when using something that doesn't exist:
```
root@Rick:~# nc localhost 3493 -v
Rick [127.0.0.1] 3493 (nut) open
LIST VAR somenoexistent
ERR UNKNOWN-UPS
root@Rick:~# 
```
I need to add the field to the Unraid XML.
Until then as a workaround you can add `UPS_ALIAS` as a variable to the Unraid container and give the value the name of your UPS and just restart the container.

**Comment by agit22** [comment]
It's a PowerWalker VI 2000 LCD UPS. And yes, adding the variable `UPS_ALIAS="name"` fixed it. Working as intended now.

**Comment by mcindea** [comment]
OK, so I also added the variable to the UI. Thanks to @Squidly271 for fixing it.
Also I added the exported graph just in case it's useful for you too:
https://github.com/kiwimato/nut-influxdb-exporter/blob/master/Unraid%20System%20Dashboard%20New-1577093376607.json

**Comment by mcindea** [comment]
Closing this one since there's no activity. Feel free to open other ones for any other issues.
